include_attribute "kagent"
include_attribute "spark"

default[:adam][:version]             = "0.15.0"
default[:adam][:user]                = "#{node[:hadoop][:yarn][:user]}"
default[:adam][:group]               = "#{node[:hadoop][:group]}"
default[:adam][:dir]                 = "#{node[:spark][:dir]}"
default[:adam][:base_dir]            = "#{node[:adam][:dir]}/spark"
default[:adam][:home]                = "#{node[:spark][:dir]}/adam-distribution-#{node[:adam][:version]}"
default[adam:][:url]                 = "#{node[:download_url]}/adam-distribution-#{node[:adam][:version]}-bin.tar.gz"
